[package]
name = "sorting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1"
num_cpus = "1"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "merge_sort_benchmark"
harness = false